baseURL = 'https://www.tsaiggo.life/'
languageCode = 'en-us'
title = "tsaiggo's blog"
theme = 'PaperMod'

[params]
    [params.homeInfoParams]
        Title = "Hi, I'm tsaiggo!"
        Content = "野生服务端程序员 ｜ 闲来无事喜欢做饭 ｜ 奶茶收割机 ｜ 喜欢买书 ｜ 啥都学，啥都不精"

    [socialIcons]
        name = 'github'
        url = "https://github.com/adityatelange/hugo-PaperMod"