baseURL = 'https://www.tsaiggo.life/'
languageCode = 'en-us'
title = "tsaiggo's blog"
theme = 'ghostwriter'

[markup]
    [markup.highlight]
        anchorLineNos = false
        codeFences = true
        guessSyntax = false
        hl_Lines = ''
        lineAnchors = ''
        lineNoStart = 1
        lineNos = false
        lineNumbersInTable = true
        noClasses = true
        style = 'monokai'
        tabWidth = 4